cmake_minimum_required(VERSION 3.24)
project(3d)
set(CMAKE_CXX_STANDARD 17)
find_package(PkgConfig)

if(USE_GUI OR USE_AUTH)
    find_package(Qt5 REQUIRED COMPONENTS Widgets Sql)
endif ()

if(USE_GUI OR USE_AUTH)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTORCC ON)
    set(CMAKE_AUTOUIC ON)
    qt_add_resources(RESOURCES icons.qrc)
endif ()

if(USE_PATH)
    add_executable(${CMAKE_PROJECT_NAME}_1 Primitives.h Polygons.cpp Polygons.h clipper.cpp clipper.hpp ${RESOURCES} main.cpp)
endif ()

if(USE_SLICER)
    add_executable(${CMAKE_PROJECT_NAME}_2 main_slice.cpp ModelSlicer.cpp ModelSlicer.h Primitives.h stlParser.cpp Polygons.cpp Polygons.h clipper.cpp clipper.hpp ${RESOURCES})
endif ()
if(USE_AUTH)
    add_definitions(-DUSE_AUTH)
endif ()
if(USE_GUI OR USE_AUTH)
   add_executable(${CMAKE_PROJECT_NAME}_3 main_auth.cpp ModelSlicer.cpp ModelSlicer.h Primitives.h myarea.cpp myarea.h stlParser.cpp Polygons.cpp Polygons.h loginWindow.cpp loginWindow.h SliceWindow.cpp SliceWindow.h authmanager.h authmanager.cpp clipper.cpp clipper.hpp ${RESOURCES} userstab.cpp userstab.h)
   target_link_libraries(${CMAKE_PROJECT_NAME}_3 Qt5::Widgets Qt5::Sql)
endif ()
